services:
  frontend:
    image: postmodern.alexdaniel.org/crylendar-frontend:latest
    build:
      context: .
    networks:
      - caddy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      restart_policy:
        delay: 1s
        window: 120s

      labels:
        caddy: crylendar.org
        caddy.tls: alex.jakimenko+caddy@gmail.com
        caddy.reverse_proxy: '{{upstreams 80}}'
        # caddy.try_files: "{path} /"

networks:
  caddy:
    external: true
