services:
  backend:
    image: postmodern.alexdaniel.org/crylendar-backend:latest
    environment:
      DB_HOST: crylendar-db_postgres
      DB_PORT: 5432
      DB_NAME: crylendar
      DB_USER: crylendar
      DB_PASSWORD: crylendar
    build:
      context: .
    networks:
      - caddy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first

      labels:
        caddy: crypi.crylendar.org
        caddy.tls: alex.jakimenko+caddy@gmail.com
        caddy.reverse_proxy: "{{upstreams 3000}}"
        # caddy.try_files: "{path} /"

networks:
  caddy:
    external: true
